### ISSUE TITLE
Support for OpenBSD... of course

### ISSUE THREAD

**Issue by anoduck** [doctorfree/Asciiville#9]
Since this is the greatest technological achievement created by mankind, I will have to tinker with it and get it running on OpenBSD. Shouldn't be too much of a hassle. I would do it now, but it is already early morning here.

Just the usual stuff, call `gdiff` instead of `diff`, same with `cp`. Ensure it installs to `/usr/local/bin` or `~/bin`, anything but `/usr/bin`. 

I can't wait to tell my friends!

**Comment by doctorfree** [comment]
@anoduck good idea, an OpenBSD port would be great. I've got good news and bad news for you. Since it is early morning here I will start with the good news. There is already a script that prepares an installation tarball that extracts into `/usr/local`, see [pkg/mktgz.sh](https://github.com/doctorfree/Asciiville/blob/main/pkg/mktgz.sh). This is currently only for macOS but could be used as a starting point for other platforms.

Unfortunately, the bad news is pretty bad. After installation, Asciiville requires post-installation configuration with the `ascinit` script. Several utilities are installed during this process including some that are pre-packaged in Linux packaging formats or, on macOS, with Homebrew. So a port to an additional platform will require packaging of binary distributions for some utilities (maybe these already exist for OpenBSD?) and modifying `ascinit` to recognize the platform and download the appropriate packages. I don't think it will be easy.

**Comment by anoduck** [comment]
@doctorfree As previously stated, in all dear truthfulness, Asciiville is the greatest innovation since Macaroni and Cheese. It is WAY more feature packed than I ever anticipated.

I am exhausted, so I will have to be frank in order to make sense. I will dive into it as I use it on my Kali development server. Right now, life is rather mission-critical, and nose to the grind stone. So, I don't know when I will get to it. There is so much to learn, and time is so fleeting. 

I am just thankful that you reached out for a response, and were friendly and sincere. Until things chill down, on the back burner it will have to go. 

Thanks for the response, blessings.
